### ISSUE TITLE
Need troubleshooting 

### ISSUE THREAD

**Issue by saraswatkarthik** [saraswatkarthik/JB-Tech-Classes#1]
https://github.com/saraswatkarthik/JB-Tech-Classes/blob/95a20d1c17e6d2ef28c3006fa7323f6156664502/index.html#L7

Bootstrap resources are not loading troubleshoot this.

**Comment by amar-prabhu-29** [comment]
You'll Need to close the opened double quotes on the previous line 

```
<meta name="viewport" content="width=device-width, initial-scale=1**"**>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
```

**Comment by skpandey885** [comment]
hey! can I fix it?

**Comment by saraswatkarthik** [comment]
it's fixed thanks for your attention!
